name: deploy

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'   # publish on version tag like v1.0.0

jobs:
  deploy:
    environment: PROD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.x.x    
    
    - name: Pack
      run: dotnet pack src/NBomber.Sinks.OpenTelemetry/NBomber.Sinks.OpenTelemetry.csproj -c Release -o artifacts --include-source
      
    - name: Publish
      run: dotnet nuget push artifacts/**.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
